# Base configs
baseurl: "http://gabrielasphotography.club"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Gabriela's Photography Portfolio"
subtitle: "See the world through my eyes!"
author: "Gabriela Doina"
header:
 title: "Photography"
 subtitle: "by Gabriela Doina"
footer:
 name: "Hey there, my name is Gabriela"
 bio: "I am an amateur passionate photographer"
web_design: "Marian Adrian"
social_urls:
  facebook: "https://www.facebook.com/gabriela.gadescu"
  twitter: "https://twitter.com/Gabrielagadescu"
  instagram: "https://www.instagram.com/gabrielagadescu/"
  linkedin: "https://www.linkedin.com/in/doina-gabriela-nicoara-5157a6123/"
